version: '3.8'

services:
  mysql:
    image: mysql:8.4.6
    container_name: db_container_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: meubanco
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin123
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
